apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort        # 👈 THIS was missing
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
